@base = http://localhost:3000

#### GET
GET {{base}}/auth/login



#### POST
POST {{base}}/auth/registro
Content-Type: application/json

{
    "nombre": "Joaquin",
    "email": "juako.r@gmail.com",
    "password": "juako90",
}


# GET {{base}}/prestamo/reporte/solicitud
# Authorization: Bearer {{token}}
# Content-Type: application/json

# {
#     "id": 32
# }